server:
  port: 9006

spring:
  application:
    name: seafood-order-9006
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://127.0.0.1:3306/seafood_sell_system?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456

feign:
  httpclient:
    enabled: true

mybatis:
  mapperLocations: classpath:mapper/*.xml
  #所有entity别名类所在包
  type-aliases-package: com.victor.seafoodback.entity
  configuration:
    map-underscore-to-camel-case: true